---
# #tasks file for roles/create-user-group-role
#
# Group needs to be created first.
# Password need to be encrypted
# DevOps 2022
#
#
   - name: Creatting Group with role
     ansible.builtin.group:
        name: "tomcat"

   - name: Creatiing User with role
     ansible.builtin.user:
        name: "tomcat"
        password: "{{ 'tomcat' | password_hash('sha512') }}"
        createhome: yes
        group: "tomcat"
        state: present
     register: users_manage_user
