---
- name: create users
  hosts: all
  gather_facts: false
  become: true
  vars:
   users:
     - "test1"
     - "test2"
     - "test3"
  tasks:
    - user:
       name: "{{ item }}"
       state: present
      with_items: "{{ users }}"
       #loop: "{{ users }}"
