---
    - name: Install httpd package
      dnf:
       name: httpd
       state: present

    - name: Start httpd service
      service:
       name: httpd
       state: started

    - name: Create index.html using Jinj2
      template:
       src: index.j2
       dest: /var/www/html/index.html
      notify: restart httpd

